import { Award, GraduationCap } from "lucide-react";
import type { TimelineEvent } from "@/components/ui/Timeline";

/** Career timeline shown on /about (bundled data until it is modelled in Sanity). */
export const ABOUT_TIMELINE: TimelineEvent[] = [
  // Education
  {
    date: new Date("2006-06-01"),
    title: "Graduated College",
    description: "Completed undergraduate studies",
    type: "education",
    icon: <GraduationCap className="h-6 w-6" />,
  },
  // MVP Awards (announced in January each year)
  {
    date: new Date("2026-01-15"),
    title: "Sitecore MVP 2026",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2026-Technology.png",
    imageAlt: "Sitecore MVP 2026",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
  {
    date: new Date("2025-01-15"),
    title: "Sitecore MVP 2025",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2025-Technology.png",
    imageAlt: "Sitecore MVP 2025",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
  {
    date: new Date("2022-01-15"),
    title: "Sitecore MVP 2022",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2022-Technology.png",
    imageAlt: "Sitecore MVP 2022",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
  {
    date: new Date("2021-01-15"),
    title: "Sitecore MVP 2021",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2021-Technology.png",
    imageAlt: "Sitecore MVP 2021",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
  {
    date: new Date("2020-01-15"),
    title: "Sitecore MVP 2020",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2020-Technology.png",
    imageAlt: "Sitecore MVP 2020",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
  {
    date: new Date("2019-01-15"),
    title: "Sitecore MVP 2019",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2019-Technology.png",
    imageAlt: "Sitecore MVP 2019",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
  {
    date: new Date("2018-01-15"),
    title: "Sitecore MVP 2018",
    description: "Recognized as a Sitecore Most Valuable Professional in Technology",
    type: "award",
    icon: <Award className="h-6 w-6" />,
    image: "/images/2018-Technology.png",
    imageAlt: "Sitecore MVP 2018",
    link: "https://mvp.sitecore.com/en/Directory/Profile?id=29e76e11e5af446b367b08dd46ae56e7",
    badge: "Technology MVP",
  },
];
